services:
  - type: web
    name: portfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn portfolio_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
    postdeploy: "python manage.py migrate"
