services:
  - type: web
    name: pradeeptadi-portfolio
    env: python
    buildCommand: ""
    startCommand: |
      python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
